---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Update repository index for CentOS box
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install httpd package on CentOS box
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Add php support for httpd on CentOS box
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
